spring:
  jpa:
    properties:
      hibernate:
      show_sql: false
      format_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true